package actions

const MAX_PLAYER_HEALTH = 100
const MAX_MONSTER_HEALTH = 100
const MIN_PLAYER_HEALTH = 0
const MIN_MONSTER_HEALTH = 0
const MIN_PLAYER_ATTACK_HEALTH = 5
const MAX_PLAYER_ATTACK_HEALTH = 10
const MIN_PLAYER_HEAL = 5
const MAX_PLAYER_HEAL = 10
const MIN_PLAYER_SPECIAL_ATTACK_HEALTH = 10
const MAX_PLAYER_SPECIAL_ATTACK_HEALTH = 20
const MIN_MONSTER_ATTACK_HEALTH = 10
const MAX_MONSTER_ATTACK_HEALTH = 15
